[package]
name = "parslers-branflakes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parslers = "0.1.1"
parslers-macro = "0.1.0"